import { randomUUID } from "node:crypto";

import {
  aiTrackingProposalSchema,
  businessContextSchema,
  projectInspectionSchema,
  trackingPlanSchema,
  WIZARD_VERSION,
  type AiTrackingProposal,
  type BusinessContext,
  type ProjectInspection,
  type TrackingPlan,
} from "@usermaven/wizard-schemas";

import { canonicalJsonDigest } from "./canonical.js";

const PROMPT_VERSION = "ai-tracking-plan-v1";

function digestBusinessContext(context: BusinessContext): string {
  return canonicalJsonDigest(context);
}

export interface CreateAiTrackingPlanInput {
  inspection: ProjectInspection;
  businessContext: BusinessContext;
  aiProposal: AiTrackingProposal;
}

export interface CreateAiTrackingPlanOptions {
  now?: () => Date;
  idFactory?: () => string;
}

/**
 * Validates and stamps a proposal generated by the calling AI agent. The core
 * does not invoke a model or upload repository source.
 */
export function createAiTrackingPlan(
  input: CreateAiTrackingPlanInput,
  options: CreateAiTrackingPlanOptions = {},
): TrackingPlan {
  const inspection = projectInspectionSchema.parse(input.inspection);
  const businessContext = businessContextSchema.parse(input.businessContext);
  const proposal = aiTrackingProposalSchema.parse(input.aiProposal);
  const revenueEvents = proposal.events.filter((event) => event.revenue);

  if (revenueEvents.length > 0 && businessContext.revenue?.enabled !== true) {
    throw new Error(
      "AI-generated revenue events require explicit enabled revenue context",
    );
  }
  const warnings = [...proposal.warnings];
  if (inspection.scan.truncated) {
    warnings.push(
      "The normalized repository inspection was truncated; the AI proposal may have incomplete implementation evidence.",
    );
  }
  if (inspection.project.framework === "unknown") {
    warnings.push(
      "The framework is unknown; every proposed trigger location requires manual confirmation.",
    );
  }
  const otherProviders = [
    ...new Set(
      [
        ...inspection.analytics_dependencies.map(
          (dependency) => dependency.provider,
        ),
        ...inspection.instrumentation.map((item) => item.provider),
      ].filter((provider) => provider !== "usermaven"),
    ),
  ].sort();
  if (otherProviders.length > 0) {
    warnings.push(
      `Existing analytics providers detected (${otherProviders.join(", ")}); review coexistence, migration, and duplicate-event risk.`,
    );
  }

  return trackingPlanSchema.parse({
    schema_version: "1",
    plan_id: `plan_${(options.idFactory ?? randomUUID)()}`,
    identity: proposal.identity,
    events: proposal.events,
    shared_properties: proposal.shared_properties,
    proposal: {
      mode: "ai_generated",
      review_required: true,
      generated_by: {
        ...proposal.generated_by,
        prompt_version: PROMPT_VERSION,
      },
      business_context_digest: digestBusinessContext(businessContext),
      assumptions: proposal.assumptions,
      warnings: [...new Set(warnings)],
      source: {
        framework: inspection.project.framework,
        inspected_at: inspection.inspected_at,
        inspection_truncated: inspection.scan.truncated,
      },
    },
    created_at: (options.now ?? (() => new Date()))().toISOString(),
    wizard_version: WIZARD_VERSION,
  });
}
