import type {
  ApplyResult,
  SetupPlan,
  VerificationResult,
} from "@usermaven/wizard-schemas";

export interface BuildSetupReportInput {
  plan: SetupPlan;
  applyResult?: ApplyResult;
  verificationResult?: VerificationResult;
  generatedAt: string;
}

function operationStatus(
  operationId: string,
  requiresApproval: boolean,
  applyResult: ApplyResult | undefined,
): string {
  if (!applyResult) return requiresApproval ? "planned" : "manual";
  const applied = applyResult.operations.find(
    (operation) => operation.operation_id === operationId,
  );
  if (applied) return applied.outcome;
  return requiresApproval ? "not applied" : "manual";
}

/**
 * Renders a human-readable setup report from artifacts the caller already
 * holds. Content is derived from the plan and normalized results only — it
 * never includes environment values or captured payloads.
 */
export function buildSetupReport(input: BuildSetupReportInput): string {
  const { plan, applyResult, verificationResult } = input;
  const workspace = plan.workspace;
  const mode = plan.tracking_plan.proposal?.mode ?? "unknown";
  const lines: string[] = [
    "# Usermaven setup report",
    "",
    `Generated by \`@usermaven/wizard\` ${plan.wizard_version} on ${input.generatedAt}.`,
    "",
    "## Summary",
    "",
    `- Framework: ${plan.project.framework} (package manager: ${plan.project.package_manager})`,
    `- Workspace: ${workspace.display_name} (region: ${workspace.region})`,
    `- Tracking host: ${workspace.tracking_host}`,
    `- Tracking plan: ${mode === "deterministic_baseline" ? "baseline (automatic page views only)" : mode} with ${plan.tracking_plan.events.length} event(s) and ${plan.tracking_plan.identity.length} identity item(s)`,
    `- Setup plan: ${plan.plan_id}`,
    applyResult
      ? `- Apply outcome: ${applyResult.outcome}`
      : "- Apply outcome: not applied yet",
    verificationResult
      ? `- Verification outcome: ${verificationResult.outcome}`
      : "- Verification outcome: not verified yet",
    "",
    "## Operations",
    "",
    "| Operation | Type | Status | Summary |",
    "| --- | --- | --- | --- |",
  ];
  for (const operation of plan.operations) {
    lines.push(
      `| \`${operation.id}\` | ${operation.type} | ${operationStatus(
        operation.id,
        operation.requires_approval,
        applyResult,
      )} | ${operation.summary.replaceAll("|", "\\|")} |`,
    );
  }
  lines.push(
    "",
    "## Environment variables",
    "",
    `Set these in \`.env.local\` and in your hosting platform before building:`,
    "",
    `- \`${workspace.key_env_var ?? "USERMAVEN_PUBLIC_KEY"}\` — your workspace public key (from Workspace settings in Usermaven)`,
    `- \`${workspace.tracking_host_env_var ?? "USERMAVEN_TRACKING_HOST"}\` — \`${workspace.tracking_host}\``,
    "",
    "The wizard never reads or writes environment values; configure them",
    "yourself and keep populated env files out of version control.",
    "",
    "## Next steps",
    "",
    "1. Start the app and confirm events arrive in your Usermaven workspace.",
    "2. Ship it: see the deployment guide for Vercel, Netlify, Docker, and CI",
    "   (https://github.com/usermaven/wizard/blob/main/docs/deployment.md).",
    "3. Add custom events with an AI tracking plan",
    "   (https://github.com/usermaven/wizard/blob/main/docs/ai-tracking-plans.md).",
    "",
  );
  if (plan.risks.length > 0) {
    lines.push("## Review notes", "");
    for (const risk of plan.risks) lines.push(`- ${risk}`);
    lines.push("");
  }
  return lines.join("\n");
}
